### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by BenBals** [fsr-de/pretix-wallet#1]
Since this is not a PR, there is no good way to review this. So here we go.

1. Don't use `setup.py`, use the `pip install -e .` thingy. See our other plugins for inspiration.
2. Provide info in `pyproject.toml`
3. When I activate the payment provider for an event, it doesn't show up. Do I need to do additional configuration? -> Yes migrations
<img width="1158" alt="Screenshot 2024-03-12 at 12 42 11" src="https://github.com/fsr-de/pretix-wallet/assets/2546622/19ce69a9-f193-4d5c-a44b-749ec5c1a65d">
4. Please include the migrations in the (dev) setup instructions. That took me a while to figure out.
5. Please use the correct VerDE color for the header.
6. The next in the transaction list overflows.
<img width="1456" alt="Screenshot 2024-03-12 at 13 54 39" src="https://github.com/fsr-de/pretix-wallet/assets/2546622/1ff8b9f9-af58-4064-826b-70521b8398b8">
7. This hint doesn't seem to be true
<img width="1131" alt="Screenshot 2024-03-12 at 14 01 50" src="https://github.com/fsr-de/pretix-wallet/assets/2546622/56e95922-4fc9-43a2-af6c-6b02cab7879e">
8. Transactions don't have the right descriptions and icons in the overview
<img width="1369" alt="Screenshot 2024-03-12 at 14 02 38" src="https://github.com/fsr-de/pretix-wallet/assets/2546622/bdf15948-cee7-49a6-83ac-fdb3f862d106">
9. Include a log out button.

**Comment by jeriox** [comment]
No, it should show up right away... You activated the plugin as well as the payment provider?

**Comment by BenBals** [comment]
Ah, the migration seems to have fixed the problem.

**Comment by BenBals** [comment]
<img width="1359" alt="Screenshot 2024-03-12 at 13 59 17" src="https://github.com/fsr-de/pretix-wallet/assets/2546622/e78a2419-b1b0-4d39-a8ca-19987fbecd2c">

![Uploading Screenshot 2024-03-12 at 13.59.03.png…]()

**Comment by jeriox** [comment]
I didn't bother with the colors and overflow as @dasGoogle said in a slack thread that he wanted to beautify the view

**Comment by jeriox** [comment]
Yeah writing docs is unchecked on my todo-list in slack :P the README is just the one that comes with the pretix plugin template

**Comment by dasGoogle** [comment]
I can work on the styling. However, ist the pairing process already implemented?

**Comment by jeriox** [comment]
@dasGoogle yes

**Comment by BenBals** [comment]
Could we also enable creating custom refund for orders not originally made via VerDE Wallet? That should be relatively easy to steal from the old plugin.

**Comment by BenBals** [comment]
Haven't checked the pairing process but everything else looks good!

**Comment by BenBals** [comment]
Is there a way for the VerDE finance person to create a wallet for a person who hasn't logged in yet? That would be great for charing wallet and would save them a lot of hassle.

**Comment by jeriox** [comment]
@BenBals did we actually use that at some point?

**Comment by jeriox** [comment]
@BenBals currently not, and I'm not sure if that is possible. If we created the account manually, the pretix code would probably not allow a login via OIDC as the connection to the user there is not available

**Comment by BenBals** [comment]
> @BenBals did we actually use that at some point?

I think so, but I can swear to that. At least of the old system, it was very straightforward to implement. You should be able to steal all the code expect for the line 315 ff in `execute_refund` (but which are simply performing a negative transaction on the wallet via the api).

**Comment by BenBals** [comment]
> @BenBals currently not, and I'm not sure if that is possible. If we created the account manually, the pretix code would probably not allow a login via OIDC as the connection to the user there is not available

Could we simply create a gift card for them and on first login, the plugin checks if there already is a gift card with their name and links it?

**Comment by dasGoogle** [comment]
We don't really want to as we try to abstract from names.

**Comment by BenBals** [comment]
```python
secret=f"{request.customer.email.split('@')[0]}-{gen_giftcard_secret(length=request.organizer.settings.giftcard_length)}")
```

This scheme breaks if we open up the FSR Keycloak as discussed. Maybe do it this way for HPI Addresses and slugify all others?

**Comment by BenBals** [comment]
> We don't really want to as we try to abstract from names.

Hmm, but it's very often that people give us money before they create their account and we have to hound them basically forever afterwards. Is there so way around that?

**Comment by dasGoogle** [comment]
The paring process will now change anyways as we require all users to pair their transponder to their account before using the system. 

So I'd hope that the described case does not really happen anymore. 

If we absolutely want it, we'd need to go back to using usernames, at least temporarily.

**Comment by BenBals** [comment]
What would the alternatives be? We could print instructions on the envelopes people use to give us money?

**Comment by dasGoogle** [comment]
That sounds like a really good idea that also is pretty easy to accomplish.

**Comment by dasGoogle** [comment]
We could provide users with a 4-5 digit "charging" code to make it more obvious that you actually need it. 

But that might also make it more difficult.

**Comment by BenBals** [comment]
I'd be hesitant to make charing more difficult as we already deal with people not doing it…

**Comment by dasGoogle** [comment]
Regarding styling and review: I honestly don't have any experience with setting up pretix plugins in a dev environment. I will review once documentation exists. Don't wanna sink another hour into this.

**Comment by jeriox** [comment]
@dasGoogle well, actually: so far we asked them to give us the HPI/OIDC username. this is not represented anymore (apart from the first part of the email address which goes into the giftcard code, which you already debated earlier). assigning a wallet-id/pairing code would also make the lookup much more reliable for the person that does the topup as we could use it as part of the giftcard code and it won't change with e.g. a namechange

**Comment by jeriox** [comment]
@dasGoogle well the docs in the readme work, they just miss that you have to run the migrations after installing the plugin

**Comment by BenBals** [comment]
(Run `python3 manage.py migrate` from `src` in your pretix folder.)

**Comment by BenBals** [comment]
Also the readme doesn't include documentation on other necessary configuration (e.g., enabling customer accounts).

**Comment by dasGoogle** [comment]
In the pairing process, this appears to display the wrong email address. I am signed in in the myhpi-testing realm but it appears to use the email of the admin account that I am signed in with.
![image](https://github.com/fsr-de/pretix-wallet/assets/16378455/6408a7de-2db3-4bd6-a943-d4f7bbc207de)

The pairing does however succeed.

**Comment by dasGoogle** [comment]
I don't know where this cappucino comes from, I only added money via a manual transaction.

![image](https://github.com/fsr-de/pretix-wallet/assets/16378455/ef639c2f-a057-49e2-9fb1-f91afa9e417b)

Edit: Another Icon would probably also be nice.

**Comment by dasGoogle** [comment]
It appears as though we are still missing a logout button in the wallet web view

**Comment by dasGoogle** [comment]
We can get a full name from the KeyCloak, don't we wanna use that here? 

![image](https://github.com/fsr-de/pretix-wallet/assets/16378455/5d07c4c8-9eee-4956-96f7-6ec47a9b5935)

**Comment by dasGoogle** [comment]
From what I can tell, the customer accounts feature does not update the properties of a user (i.e., the name) on login. Can we change that?

**Comment by jeriox** [comment]
> I don't know where this cappucino comes from, I only added money via a manual transaction.
> 
> ![image](https://private-user-images.githubusercontent.com/16378455/312517839-ef639c2f-a057-49e2-9fb1-f91afa9e417b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDAzOTAsIm5iZiI6MTcxMDQ0MDA5MCwicGF0aCI6Ii8xNjM3ODQ1NS8zMTI1MTc4MzktZWY2MzljMmYtYTA1Ny00OWUyLTlmYjEtZjkxYWZhOWU0MTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE4MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYWMwODk1NDc4ZmI4ZDFlYmE5Y2U2NzYwY2Y1Y2U0MzgxOGViOGQ5Y2JkZjdkY2JiMjBlNmY5ZTAxODkyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW4ysBhRBi64wecnVKA1EHRNViLMHCoXYc1YtPQ44VQ)
> 
> Edit: Another Icon would probably also be nice.

For me that was part of "make it pretty" and I left that to you ^^

**Comment by jeriox** [comment]
> It appears as though we are still missing a logout button in the wallet web view

I had one, but it refers you to the customer account login page afterwards, I didn't like that so I removed it again

**Comment by jeriox** [comment]
> We can get a full name from the KeyCloak, don't we wanna use that here?
> 
> ![image](https://private-user-images.githubusercontent.com/16378455/312519523-5d07c4c8-9eee-4956-96f7-6ec47a9b5935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDAzOTAsIm5iZiI6MTcxMDQ0MDA5MCwicGF0aCI6Ii8xNjM3ODQ1NS8zMTI1MTk1MjMtNWQwN2M0YzgtOWVlZS00OTU2LTk2ZjctNmVjNDdhOWI1OTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE4MTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ODdlNTk4ODAyNzUzN2MzYTMyMzFkM2I2MDBhY2JlNDMyYTE5OGI1ZDkwNDE2YmMxNWFkZGIzNzE3OWMzYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bAWlWYtKGdNxoFBQDbgHXibS_iMpaERAhi_moG1MHiY)

for me this was emtpy when testing locally, but maybe I just misconfigured something in my keycloak

**Comment by jeriox** [comment]
> From what I can tell, the customer accounts feature does not update the properties of a user (i.e., the name) on login. Can we change that?

upstream

**Comment by jeriox** [comment]
as this became one hell of an issue, I moved everything to separate issues. please open additional issues for new stuff.
