### ISSUE TITLE
Wallets for users that have not logged in yet / Pairing codes

### ISSUE THREAD

**Issue by jeriox** [fsr-de/pretix-wallet#11]
previous discussion in #1:

Ben: Is there a way for the VerDE finance person to create a wallet for a person who hasn't logged in yet? That would be great for charing wallet and would save them a lot of hassle.

Julian: currently not, and I'm not sure if that is possible. If we created the account manually, the pretix code would probably not allow a login via OIDC as the connection to the user there is not available

Ben: Could we simply create a gift card for them and on first login, the plugin checks if there already is a gift card with their name and links it?

Aaron: We don't really want to as we try to abstract from names.

Ben:  (snip code) This scheme breaks if we open up the FSR Keycloak as discussed. Maybe do it this way for HPI Addresses and slugify all others?
Ben: Hmm, but it's very often that people give us money before they create their account and we have to hound them basically forever afterwards. Is there so way around that?

Aaron: The paring process will now change anyways as we require all users to pair their transponder to their account before using the system.  So I'd hope that the described case does not really happen anymore. If we absolutely want it, we'd need to go back to using usernames, at least temporarily.

Ben: What would the alternatives be? We could print instructions on the envelopes people use to give us money?

Aaron: That sounds like a really good idea that also is pretty easy to accomplish.
Aaron: We could provide users with a 4-5 digit "charging" code to make it more obvious that you actually need it. But that might also make it more difficult.

Ben: I'd be hesitant to make charing more difficult as we already deal with people not doing it…

Julian: well, actually: so far we asked them to give us the HPI/OIDC username. this is not represented anymore (apart from the first part of the email address which goes into the giftcard code, which you already debated earlier). assigning a wallet-id/pairing code would also make the lookup much more reliable for the person that does the topup as we could use it as part of the giftcard code and it won't change with e.g. a namechange

**Comment by BenBals** [comment]
I've spiked topping up VerDE wallet via buying tickets in Pretix and it works really well. So my take on this issue, would be  to just ignore it and phase out cash payments.

**Comment by dasGoogle** [comment]
That is, however, something we should check with Jonas

**Comment by BenBals** [comment]
Yes, definitely!

**Comment by BenBals** [comment]
You can find a first implementation at #12

**Comment by jeriox** [comment]
we will not implement this
