### ISSUE TITLE
Product endpoint metadata

### ISSUE THREAD

**Issue by jeriox** [fsr-de/pretix-wallet#2]
do we still want to keep the metadata on the endpoint that returns all products?

**Comment by jeriox** [comment]
@dasGoogle is there any reason why the terminal needs the metadata?

**Comment by dasGoogle** [comment]
All I need is the products. I believe that I can strip anything else from the terminal

**Comment by jeriox** [comment]
@dasGoogle okay, just tell me after you tried, then I'll remove the code

**Comment by dasGoogle** [comment]
Okay, but you'll have to wait until sometime next week.

**Comment by jeriox** [comment]
@dasGoogle no problem. as said, the current version returns the resource according to the old API docs. So this is just tidying up but not a blocker

**Comment by dasGoogle** [comment]
Works, I now only parse the items property

**Comment by jeriox** [comment]
removed in [ffed9c1](https://github.com/fsr-de/pretix-wallet/commit/ffed9c1df8d0e75ce15b4bdf5e7cd7176fb9a19d)
