### ISSUE TITLE
Display full name instead of email

### ISSUE THREAD

**Issue by jeriox** [fsr-de/pretix-wallet#9]
We can get a full name from the KeyCloak, don't we wanna use that here? 

![image](https://github.com/fsr-de/pretix-wallet/assets/16378455/5d07c4c8-9eee-4956-96f7-6ec47a9b5935)

_Originally posted by @dasGoogle in https://github.com/fsr-de/pretix-wallet/issues/1#issuecomment-1994661751_

**Comment by jeriox** [comment]
@dasGoogle for me this was emtpy when testing locally, but maybe I just misconfigured something in my keycloak

**Comment by dasGoogle** [comment]
I'll check again, but I am relatively certain that this did indeed work as this was where I noticed that names were not updated (or for that matter, set in the first place) after the account is created. I used the myhpi testing realm in our keycloak (edited the allowed redirect URLs for the myHPI client there as well) and set the corresponding OIDC property in prefix to "name", if you want to try it yourself.

**Comment by jeriox** [comment]
jup works

**Comment by jeriox** [comment]
changed in https://github.com/fsr-de/pretix-wallet/commit/19815b4ae4a20abbfc331895ac8ff8a93f5242ce
